import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import "../styles/globals.css";
import Head from "next/head";
import { MyContextProvider } from "../context/myContext";

function MyApp({ Component, pageProps }) {
  return (
    <MyContextProvider>
      <Head>
        <title>Anime & Jokes</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://iconape.com/wp-content/files/vc/201433/png/201433.png"
        />
      </Head>
      <Navbar />

      <Component {...pageProps} />

      <Footer />
    </MyContextProvider>
  );
}

export default MyApp;
