import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { Fade } from "react-reveal";
import CrushIntro from "../components/CrushIntro";
import Intro from "../components/Intro";
import bg from "../public/1.gif";

export async function getServerSideProps() {
  // const anime_res = await fetch("https://anime-facts-rest-api.herokuapp.com/api/v1");
  // const anime_data = await anime_res.json();

  const kiss_res = await fetch("https://waifu.pics/api/sfw/kiss");
  const kiss_data = await kiss_res.json();

  const happy_res = await fetch("https://waifu.pics/api/sfw/happy");
  const happy_data = await happy_res.json();

  const meme_res = await fetch("https://api.catboys.com/img");
  const meme_data = await meme_res.json();

  const smile_res = await fetch("https://waifu.pics/api/sfw/smile");
  const smile_data = await smile_res.json();

  const kill_res = await fetch("https://waifu.pics/api/sfw/kill");
  const kill_data = await kill_res.json();
  return {
    props: {
      // animes: anime_data.data,
      kiss: kiss_data,
      happy: happy_data,
      kill: kill_data,
      meme: meme_data,
      smile: smile_data,
    },
  };
}

export default function Home({ kiss, happy, kill, meme, smile }) {
  const [loading, setLoading] = useState(false);
const styling = {
    backgroundImage: `url('${bg}')`,
    width:"100%",
    height:"100%"
}

  return (
    <div>
      <Head>
        <title>Animes & Jokes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div >
         <Fade bottom>
        <CrushIntro loading={loading} pic={kiss} setLoading={setLoading} />
         
        
        <Intro
          loading={loading}
          pic={kill}
          setLoading={setLoading}
          title={"Animes quotes"}
          paragraph={"get quotes of your favourite Animes Character's Quote Like Ergo Proxy,Haruhi Suzumiya,Basara Tōjō etc."}
          isLeft={true}
          url="/quotes"
          category={"Quotes"}
          isBtn={true}
        />
        <Intro
          loading={loading}
          pic={smile}
          setLoading={setLoading}
          title={"Anime Collections"}
          paragraph={"Get Your Favourite Animes from various categories Like smile,selfie,milf,assetc."}
          isLeft={false}
          url="/anime"
          category={"Anime's"}
          isBtn={true}
        />
        <Intro
          loading={loading}
          pic={happy}
          setLoading={setLoading}
          title={"Funny Jokes"}
          paragraph={"Get Your Favourite Jokes from various categories Like Sex,Political,nsfw,etc."}
          isLeft={true}
          url="/joke"
          category={"Jokes"}
          isBtn={true}
        />
        <Intro
          loading={loading}
          pic={meme}
          setLoading={setLoading}
          title={"Favourite Memes "}
          paragraph={"Get Your Favourite Memes from here from various categories Like Chuck Noris,Sexist,Christmas,etc."}
          isLeft={false}
          url="/meme"
          category={"Memes"}
          isBtn={true}
        />
        </Fade>
      </div>

         
    </div>
  );
}
